## Set the API endpoint used to create the Service resource.
apiVersion: v1
## Define the type of the resource.
kind: Service
## Set the parameters that make the object identifiable, such as its name, namespace, and labels.
metadata:
  labels:
    app: visualize-current-state-depl
  name: visualize-current-state-svc
  namespace: default
## Define the desired configuration for the Service resource.
spec:
  ## Define the ports that the service should serve on. 
  ## For example, the service is exposed on port 3812, and
  ## directs the traffic to the pods on port 3812, using TCP.
  ports:
  - port: 3812
    protocol: TCP
    targetPort: 3812
  ## Identify the pods managed by this Service using the following selectors.
  ## In this case, all pods with the label `visualize-current-state`.
  selector:
    app: visualize-current-state-depl
  ## Define the Service type, here set to ClusterIP.
  type: ClusterIP